using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BethanysPieShop.Models
{
    public static class DbInitializer
    {
        /*
         Denna metoden används (nu) endast vid uppstart av applikationen

         Tips: ställ markören på "Seed" och trycker Shift-F12 så får du se var metoden används
             
        */
        public static void Seed(AppDbContext context)
        {

            if (!context.Heroes.Any())
            {
                context.AddRange
                (
                    new Hero { Name = "Naga Siren", Price = 12.95M, ShortDescription = "Slithice, while being strong in her own right, is notoriously hard to track down.", LongDescription = "Once most highly esteemed of her race, Slithice for many years commanded a battalion of her fellows, using her formidable voice as her greatest weapon. Powerful, sinuous, serpentine, she led her deadly Guard in defense of the Deep Ones, and the great wealth of the sunken cities. But in the final battle of Crey, her forces were driven back by a marauding army of levianths intent on finding tribute for their god Maelrawn. After the long and bloody onslaught, as the bodies were cleared from the sunken halls, a single jeweled chalice was found missing from the trove. Of her hundred Guard, only a handful survived, but their bravery and sacrifice were of little consequence. What mattered was that treasure was taken. Honor destroyed. And so Naga Siren was cast out. Banished to search for the stolen chalice. Though she might add a hundred times her weight to the golden trove, she is doomed to live apart until that day she returns that which was taken. For no amount of gold is equal in honor to the honor she lost.", ImageUrl = "https://cdnb.artstation.com/p/assets/images/images/004/290/369/large/halimun-ali-halimunali-nagasiren-low.jpg?1482094520", IsPieOfTheWeek = true, ImageThumbnailUrl = "https://gamepedia.cursecdn.com/dota2_gamepedia/6/60/Naga_Siren_icon.png?version=a64bc31b30d125ba993f6498b68f9a0b" },
                    new Hero { Name = "Io", Price = 18.95M, ShortDescription = "The benevolent touch of Io brings strength from between the planes.", LongDescription = "	Io is everywhere, and in all things. Denounced by enemies as the great unmaker, worshiped by scholars as the twinkling of a divine eye, this strange Wisp of life-force occupies all planes at once, the merest fraction of its being crossing into physical existence at any one moment. Like the great twin riders Dark and Light, and yet another ancient traveler whose true history is lost to the ages, Io the Wisp is a Fundamental of the universe, a force older than time, a wanderer from realms far beyond mortal understanding. Io is nothing less than the sum of all attractive and repulsive forces within the material field, a sentient manifestation of the charge that bind existence together. It is only in the controlled warping of these electrical waylines that Io's presence can be experienced on the physical plane. A benevolent, cooperative force, Io bonds its strange magnetism to others so that the power of allies might be enhanced. Its motives inscrutable, its strength unimaginable, Io moves through the physical plane, the perfect expression of the mysteries of the universe.", ImageUrl = "https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fmikestubbs%2Ffiles%2F2017%2F05%2FIO-Arcana.jpg", IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8d/Io_icon.png?version=94a7476345faa617842c26f446a26ec4" },
                    new Hero { Name = "Luna", Price = 18.95M, ShortDescription = "Selemene smites those who encroach upon the Nightsilver Woods.", LongDescription = "How had she been reduced to this? She was once the Scourge of the Plains, a merciless leader of men and beasts, and able to sow terror wherever she dared. Now she was far from her homeland, driven half mad from starvation and months of wandering, her army long dead or worse. As she stood at the edge of an ancient forest, a pair of glowing eyes spied on from an elder branch. Something beautiful and deadly sought a meal in the wilting dusk. Without a sound, it turned and left. Fury overtook her. Clutching a rust-eaten dagger, she charged after the beast determined to reclaim even a shred of her past glory, but her quarry would not be caught. Three times she cornered the creature among the rocks and trees, and three times she pounced only to witness its fading shadow darting further into the woods. Yet the full moon shone brightly, and the creature's trail was easy to follow. Arriving in a clearing atop a high hill, the beast's massive feline form sat in the open, attentive and waiting. When the woman brandished her dagger, the creature reared and roared and charged. Death, it seemed, had come for her at long last in this strange place. She stood, calm and ready. A flash of movement, and the beast snatched the dagger from her hand before vanishing into the forest. Stillness. Hooded figures approached. In reverent tones they revealed that Selemene, Goddess of the Moon, had chosen her, had guided her, had tested her. Unwittingly she had endured the sacred rites of the Dark Moon, warriors of the Nightsilver Woods. She was offered a choice: join the Dark Moon and pledge herself to the service of Selemene, or leave and never return. She did not hesitate. Embracing her absolution, she renounced her bloody past, and took up a new mantle as Luna of the Dark Moon, the dreaded Moon Rider, ruthless and ever-loyal guardian of the Nightsilver Woods.", ImageUrl = "https://media.esportsedition.com/wp-content/uploads/2016/11/Luna-1-1068x601.jpg", IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7d/Luna_icon.png?version=b1d1b20a5c17defc097201e30e83ff98" },
                    new Hero { Name = "Spectre", Price = 15.95M, ShortDescription = "Mercurial's dagger eclipses the physical plane in shadow, a state in which mortals cower, but spectres thrive.", LongDescription = "Just as higher states of energy seek a lower level, the Spectre known as Mercurial is a being of intense and violent energy who finds herself irresistibly drawn to scenes of strife as they unfold in the physical world. While her normal spectral state transcends sensory limitations, each time she takes on a physical manifestation, she is stricken by a loss of self--though not of purpose. In the clash of combat, her identity shatters and reconfigures, and she begins to regain awareness. She grasps that she is Mercurial the Spectre--and that all of her Haunts are but shadows of the one true Spectre. Focus comes in the struggle for survival; her true mind reasserts itself; until in the final moments of victory or defeat, she transcends matter and is restored once more to her eternal form.", ImageUrl = "https://i.pinimg.com/originals/14/6a/60/146a608e995b2731211ca3f9313bdae9.jpg", IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gamepedia.cursecdn.com/dota2_gamepedia/f/ff/Spectre_icon.png?version=8af2c21961605d25cfa1be31725d7422" },
                    new Hero { Name = "Earthshaker", Price = 13.95M, ShortDescription = "The Nishian totem splits the world to its core with tectonic force.", LongDescription = "	Like a golem or gargoyle, Earthshaker was one with the earth but now walks freely upon it. Unlike those other entities, he created himself through an act of will, and serves no other master. In restless slumbers, encased in a deep seam of stone, he became aware of the life drifting freely above him. He grew curious. During a season of tremors, the peaks of Nishai shook themselves loose of avalanches, shifting the course of rivers and turning shallow valleys into bottomless chasms. When the land finally ceased quaking, Earthshaker stepped from the settling dust, tossing aside massive boulders as if throwing off a light blanket. He had shaped himself in the image of a mortal beast, and named himself Raigor Stonehoof. He bleeds now, and breathes, and therefore he can die. But his spirit is still that of the earth; he carries its power in the magical totem that never leaves him. And on the day he returns to dust, the earth will greet him as a prodigal son.", ImageUrl = "https://steamcdn-a.akamaihd.net/apps/dota2/videos/international2019/earthshaker_arcana/earthshaker_arcana_header.jpg", IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a5/Earthshaker_icon.png?version=7f16a63e5ed6a7ec7a3889dd4aea354d" },
                    new Hero { Name = "Enigma", Price = 17.95M, ShortDescription = "Strange gravities pull at the core of those who would oppose you, holding them in place.", LongDescription = "Nothing is known of Enigma’s background. There are only stories and legends, most of them apocryphal, passed down through the ages. In truth, Enigma is a mystery for whom the only true biography is description: he is a universal force, a consumer of worlds. He is a being of the void, at times corporeal, other times ethereal. A beast between the planes. There are stories that say he was once a great alchemist who tried to unlock the secrets of the universe and was cursed for his arrogance. Other legends tell that he is an ancient being of strange gravity, the abyss personified—a twisted voice from out the original darkness, before the first light in the universe. And there are older legends that say he is the first collapsed star, a black hole grown complicated and sentient—his motivations unknowable, his power inexorable, a force of destruction unleashed upon existence itself.", ImageUrl = "https://i.pinimg.com/originals/5e/67/b7/5e67b721d025256d85178e446d9e3562.jpg", IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gamepedia.cursecdn.com/dota2_gamepedia/f/f7/Enigma_icon.png?version=cd786d109fe3b9bbf88f82ad48c8723b" },
                    new Hero { Name = "Meepo", Price = 15.95M, ShortDescription = "Catching dinner in the Riftshadow Ruins can be quite the task.", LongDescription = "If you ask me, life is all about who you know and what you can find. When you live up in the Riftshadow Ruins, just finding food can be tough. So you need to cut corners, you need to scrounge, you need to know your strengths. Some of the beasts up there can kill you, so you need a way to trap the weak and duck the strong. On the upside, the ruins have history, and history is worth a lot to some people. There used to be a palace there, where they had all these dark rituals. Bad stuff. If you survived the ceremony, they would shatter a crystal and split your soul into pieces. They made great art though! Sculptures and such. Let me tell you: sometimes you stumble onto some of those old carvings. Take a pack full of those to town and sell them, then get yourself food for a few weeks. If luck is really on your side, you might find a Riftshadow crystal. Get it appraised and start asking around. Someone always knows some crazy fool looking for this kind of thing. If all else fails, sell it to a Magus the next time one's in town. They love that stuff. Still, whatever you do, be careful handling those crystals. You do not want one to go off on you. It really hurts.", ImageUrl = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/69306615-010a-4f72-bffb-ec6ed4614e31/daeln3f-d52e7e61-2ce2-4237-b6bc-fe745d0680d8.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzY5MzA2NjE1LTAxMGEtNGY3Mi1iZmZiLWVjNmVkNDYxNGUzMVwvZGFlbG4zZi1kNTJlN2U2MS0yY2UyLTQyMzctYjZiYy1mZTc0NWQwNjgwZDguanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.Rv9b6Ej5k22KkAXq4OlmJIPy_3S2RpeGwPlu1GRNYs8", IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gamepedia.cursecdn.com/dota2_gamepedia/8/85/Meepo_icon.png?version=06970686c2620e4899376b9ee7e17d47" },
                    new Hero { Name = "Rubick", Price = 12.95M, ShortDescription = "Even the Grandest Magus may use his powers for enjoyment.", LongDescription = "Any mage can cast a spell or two, and a few may even study long enough to become a wizard, but only the most talented are allowed to be recognized as a Magus. Yet as with any sorcerer’s circle, a sense of community has never guaranteed competitive courtesy.Already a renowned duelist and scholar of the grander world of sorcery, it had never occurred to Rubick that he might perhaps be Magus material until he was in the midst of his seventh assassination attempt. As he casually tossed the twelfth of a string of would-be killers from a high balcony, it dawned on him how utterly unimaginative the attempts on his life had become. Where once the interruption of a fingersnap or firehand might have put a cheerful spring in his step, it had all become so very predictable. He craved greater competition. Therefore, donning his combat mask, he did what any wizard seeking to ascend the ranks would do: he announced his intention to kill a Magus.Rubick quickly discovered that to threaten one Magus is to threaten them all, and they fell upon him in force. Each antagonist's spell was an unstoppable torrent of energy, and every attack a calculated killing blow. But very soon something occurred that Rubick's foes found unexpected: their arts appeared to turn against them. Inside the magic maelstrom, Rubick chuckled, subtly reading and replicating the powers of one in order to cast it against another, sowing chaos among those who had allied against him. Accusations of betrayal began to fly, and soon the sorcerers turned one upon another without suspecting who was behind their undoing. When the battle finally drew to a close, all were singed and frozen, soaked and cut and pierced. More than one lay dead by an ally’s craft. Rubick stood apart, sore but delighted in the week’s festivities. None had the strength to argue when he presented his petition of assumption to the Hidden Council, and the Insubstantial Eleven agreed as one to grant him the title of Grand Magus.", ImageUrl = "https://www.thenerdmag.com/wp-content/uploads/2018/12/qjxhc62cftdz.png", IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8a/Rubick_icon.png?version=069f44c919f07acd1dec09aa71330568" },
                    new Hero { Name = "Lich", Price = 15.95M, ShortDescription = "Frost-mage Ethreain has not forgotten even the simplest of ice manipulation.", LongDescription = "In life, the frost-mage Ethreain (not yet a Lich) had used the threat of destructive ice to enslave entire kingdoms. His subjects, aided by a few desperate magicians, eventually grew bold enough to ambush him. Armed with enough charmed rope to bind him forever, they tied the frost mage to adamant weights and dropped him in a pool known chiefly for being bottomless. It wasn't. He only fell for a year or so before an outcrop snagged him. There he rested, dead but undecaying, until the geomancer Anhil thought to verify the legend of the supposedly bottomless Black Pool. Anhil's plumbline snarled with the ropes that bound the drowned magician, and up he hauled an unexpected prize. Thinking that by rendering the dead undead, he could question the Lich about the properties of the pool, he removed the bindings and commenced a simple rite of resurrection. Even the descendants of Ethreain's enemies were long forgotten by time, so there were none to warn Anhil against imprudence. But he learned the error of his judgment almost immediately, as Lich threw off the shackles and consumed him.", ImageUrl = "https://media.esportsedition.com/wp-content/uploads/2016/10/Lich-1068x675.jpg", IsPieOfTheWeek = false, ImageThumbnailUrl = "https://gamepedia.cursecdn.com/dota2_gamepedia/b/bb/Lich_icon.png?version=7cb34de5d2bb15610cda9474d6c1b306" }
                    );

                context.SaveChanges();
            }

        }

    }
}
